update to latest ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,18 +44,21 @@ jobs:
         dotnet reportgenerator -targetdir:'${{ github.workspace }}/drop/reports' -reports:**/coverage.cobertura.xml -reporttypes:"htmlsummary"
         rm -f ${{ github.workspace }}/drop/reports/summary.htm
         mv ${{ github.workspace }}/drop/reports/summary.html ${{ github.workspace }}/drop/reports/coverage-report.html
-    - name: Generate raw mutation data
+    - name: Get mutation data
       id: gen_mutation
       if: success() || steps.check_coverage.outcome == 'failure'
       run: |
+        returncode=0
         shopt -s extglob globstar
-        status=0
-        for testproj in *.+(Test*(s)|UnitTest*(s)); do dotnet stryker -tp "$testproj"; status=$(($status + $?)); done; exit $status
-    - name: Process mutation report
-      if: success() || steps.check_coverage.outcome == 'failure' || steps.gen_mutation.outcome == 'failure'
-      run: |
-        strykerFile=$(find ./StrykerOutput -name mutation-report.html)
-        cp $strykerFile ${{ github.workspace }}/drop/reports
+        for testproj in *.+(Test*(s)|UnitTest*(s)); do
+          echo "Generating mutants for: $testproj..."
+          iterr=$(dotnet stryker -tp "$testproj" &>/dev/null; echo $?)
+          [ $iterr != 0 ] && echo " -- failed to destroy all mutants :(" && returncode=1
+          [ $iterr == 0 ] && echo " -- you destroyed all the mutants :)"
+          echo " -- staging report to artifact location..."
+          mv ./StrykerOutput/**/mutation-report.html "${{ github.workspace }}/drop/reports/mutation-$testproj.html"
+        done
+        exit $returncode
     - name: Drop artifact - reports
       if: success() || steps.check_coverage.outcome == 'failure' || steps.gen_mutation.outcome == 'failure'
       uses: actions/upload-artifact@v3
