Update latest libary project template

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -21,6 +21,10 @@ jobs:
       run: dotnet nuget add source --name ne1410s --username ne1410s --password "${{ env.READ_REPO_PACKAGES }}" --store-password-in-clear-text "https://nuget.pkg.github.com/ne1410s/index.json"
     - name: Restore tools
       run: dotnet tool restore
+    - name: Install test prerequisites (linux)
+      run: |
+        sudo apt update
+        sudo apt install -y ffmpeg
     - name: Build for release
       run: dotnet build -c Release
     - name: Generate raw coverage data
@@ -48,13 +52,18 @@ jobs:
       id: gen_mutation
       if: success() || steps.check_coverage.outcome == 'failure'
       run: |
+        baseSha=${{ github.event.pull_request.base.sha }}
+        if [ "$baseSha" ]; then
+          git fetch &>/dev/null
+          sinceArg="--since:$baseSha"
+        fi
         returncode=0
         shopt -s extglob globstar
         for testproj in *.+(Test*(s)|UnitTest*(s)); do
           echo "Generating mutants for: $testproj..."
-          iterr=$(dotnet stryker -tp "$testproj" &>/dev/null; echo $?)
-          [ $iterr != 0 ] && echo " -- failed to destroy all mutants :(" && returncode=1
-          [ $iterr == 0 ] && echo " -- you destroyed all the mutants :)"
+          iterr=$(dotnet stryker -tp "$testproj" -f "$testproj/stryker-config.json" $sinceArg &>/dev/null; echo $?)
+          [ "$iterr" != 0 ] && echo " -- failed to destroy all mutants :(" && returncode=1
+          [ "$iterr" == 0 ] && echo " -- you destroyed all the mutants :)"
           echo " -- staging report to artifact location..."
           mv ./StrykerOutput/**/mutation-report.html "${{ github.workspace }}/drop/reports/mutation-$testproj.html"
         done
